### ISSUE TITLE
Getting "ActiveMocker.safe_methods is unable to find methods: __missing_class_macros__" error for ruby 2.5.5

### ISSUE THREAD

**Issue by mahigawas28** [zeisler/active_mocker#123]
I am getting `ActiveMocker.safe_methods is unable to find methods: __missing_class_macros__` error when try to run rake task `rake active_mocker:build` with ruby version 2.5.5

It's working fine with old version of ruby (2.4.5)

**Comment by zeisler** [comment]
I checked if I am testing that version of Ruby in travis and I am. Could you @mahigawas28 provide a little more info maybe a backtrace or an example project so I can debug the issue faster.

**Comment by mahigawas28** [comment]
@zeisler I am getting this error in lenny project of renewfiancial, please find below error log details

`AvmDbProperty has the following errors:
ActiveMocker.safe_methods is unable to find methods: __missing_class_macros__
error
ActiveMocker.safe_methods is unable to find methods: __missing_class_macros__
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator/defined_methods.rb:30:in `create_method'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator/defined_methods.rb:20:in `block in class_methods'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator/defined_methods.rb:20:in `map'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator/defined_methods.rb:20:in `class_methods'
(erb):7:in `block in partials'
/Users/mgavas/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/erb.rb:876:in `eval'
/Users/mgavas/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/erb.rb:876:in `result'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:121:in `block in partials'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:117:in `each'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:117:in `each_with_object'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:117:in `partials'
(erb):5:in `template_creator_default'
/Users/mgavas/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/erb.rb:876:in `eval'
/Users/mgavas/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/erb.rb:876:in `result'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/template_creator.rb:15:in `render'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:49:in `render'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/mock_creator.rb:44:in `create'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:72:in `create_mock'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:21:in `process!'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:15:in `block in write!'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:33:in `block in safe_write'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:31:in `open'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:31:in `safe_write'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/file_writer.rb:15:in `write!'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/generate.rb:58:in `write_file'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/generate.rb:21:in `block in call'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/generate.rb:20:in `each'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/generate.rb:20:in `call'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/active_mocker-2.6.1.beta2/lib/active_mocker/public_methods.rb:31:in `create_mocks'
/Users/mgavas/projects/lenny/tasks/active_mocker.rake:21:in `block (2 levels) in <top (required)>'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/mgavas/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/mgavas/.rvm/gems/ruby-2.5.5/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/mgavas/.rvm/gems/ruby-2.5.5/bin/rake:23:in `load'
/Users/mgavas/.rvm/gems/ruby-2.5.5/bin/rake:23:in `<main>'
/Users/mgavas/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/Users/mgavas/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
RuntimeError`

Sample model code

`require_relative "application_record"
module ReportParser
  module UnderwritingData
    # ActiveMocker.all_methods_safe
    class AvmDbProperty < ::ReportParser::UnderwritingData::ApplicationRecord
      self.table_name = "avm_db_properties"
      has_many :avm_db_property_mortgages, class_name: "ReportParser::UnderwritingData::AvmDbPropertyMortgage"


      module PropertyValueLabels
        def property_value_label
          "ez_value"
        end

        def property_attribute_name
          if self.try(:property_state) == "FL"
            "avm_high"
          else
            "high_low_avg_avm"
          end
        end
      end
      include PropertyValueLabels
      extend PropertyValueLabels

      def property_value
        return avm_valuehigh if property_state == "FL"
        avm_value_amount
      end

      def confidence_score
        avm_confidence_score
      end

      def valuation_date
        black_knight_avm_updated_at
      end

      def table_name
        self.class.table_name
      end
    end
  end
end

`

**Comment by zeisler** [comment]
@mahigawas28 can you try using the latest version and see if your issue persists?

**Comment by zeisler** [comment]
Thanks for that extra information. I can try to dig into this sometime this week.

**Comment by zeisler** [comment]
@mahigawas28 I have been trying to reproduce this error and have been unable, but I could have a solution although I am unable to test it.

Add the following monkey patch to `config/initializers/active_mocker.rb`

```ruby
module ActiveMocker
  class MockCreator
    module DefinedMethods
      def class_methods
        class_introspector
          .get_class
          .methods(false)
          .reject {|m|  [:__missing_class_macros__].include?(m.to_sym)}
          .sort
          .map { |m| create_method(m, :method) }
      end
    end
  end
end
```

If you find that there are more methods like `__missing_class_macros__` showing up add it to the array.

I know this is only a hack, but the only way I could possible find a way to fix this is for you to give me a minimal repo that reproduces the error.
