### ISSUE TITLE
Fall back for specific database types

### ISSUE THREAD

**Issue by zeisler** [zeisler/active_mocker#23]
Postgresql has JSON, Hstore and there are others that are not supported. Currently if you try to generate a mock from model that is not part of the common types the generation fails. I would like to make an AnyType that would be a fallback. Also provide a way so that a user could extend the types to add their own custom types.

**Comment by zeisler** [comment]
New DB types can be registered with this API.

[active_record_schema_scrapper/attributes.rb](https://github.com/zeisler/active_record_schema_scrapper/blob/master/lib/active_record_schema_scrapper/attributes.rb)
```ruby
ActiveRecordSchemaScrapper::Attribute.register_type(name: :array, klass: Array)
```

**Comment by fatuhoku** [comment]
@zeisler where are you supposed to put this registration code?

**Comment by zeisler** [comment]
for rails

config/initializers/active_mocker.rb
