### ISSUE TITLE
Doesn't works with db/structure.sql

### ISSUE THREAD

**Issue by lmorais** [zeisler/active_mocker#26]
Doesn't works with db/structure.sql instead of db/schema.rb

rake active_mocker:build

```
rake aborted!cks |>>                                                                                               | 0%
NoMethodError: undefined method `class_name' for #<Errno::ENOENT:0x007f4af1480e48>

Errno::ENOENT: No such file or directory @ rb_sysopen - /home/myproject/db/schema.rb

Tasks: TOP => active_mocker:build
(See full trace by running task with --trace)
```

**Comment by zeisler** [comment]
I'm sorry your having this problem. Currently active mocker is dependent on the schema.rb. One way around that I think that may work would be just to get the information from each ActiveRecord models This would take some time to do and I would be open to a pull request for this feature.

**Comment by zeisler** [comment]
After some consideration I would like to remove the schema.rb dependency for version 2.0.0. I am setting a goal to release version 2 in 3-6 months.

**Comment by zeisler** [comment]
I am happy to announce version 2.0.0.beta1. No schema.rb file required. [rubygems](https://rubygems.org/gems/active_mocker/versions/2.0.0.beta1)
