### ISSUE TITLE
Models in a NameSpace won't generate

### ISSUE THREAD

**Issue by zeisler** [zeisler/active_mocker#28]

**Comment by semikolon** [comment]
I need this too. Would be awesome...

**Comment by zeisler** [comment]
Thanks for letting me know that you need it. I will prioritize it higher.

**Comment by zeisler** [comment]
@semikolon if you use `gem "active_mocker", github: "zeisler/active_mocker"` you can try out this feature. I am not able to release a new version yet because of some environment differences in Travis that cause the build to fail.

**Comment by zeisler** [comment]
it's released: https://rubygems.org/gems/active_mocker/versions/2.1.0

**Comment by semikolon** [comment]
Hey, thanks! :) Awesome, trying it out soon
tis 9 feb. 2016 kl. 02:03 skrev Dustin Zeisler <notifications@github.com>:
