### ISSUE TITLE
Build task assumes schema.rb

### ISSUE THREAD

**Issue by krainboltgreene** [zeisler/active_mocker#32]
:(

**Comment by zeisler** [comment]
Are you using db/structure.sql? If so I am working on version 2.0 so that it will not require the schema.rb. I don't have know when it will be done, but I'm working hard on it.

**Comment by krainboltgreene** [comment]
Awesome!

**Comment by krainboltgreene** [comment]
Yes, we're using `db/structure.sql` I can't wait for 2.0! :D
