### ISSUE TITLE
Ignore Non AR subclasses

### ISSUE THREAD

**Issue by markburns** [zeisler/active_mocker#44]
I've been trying to get an isolated failing spec for this, but I don't quite fully understand the code and specs of this project yet.

If we have `Foo` and that inherits from top level class `Bar` then I'd rather not see any errors or warnings like:

```
Foo does not inherit from ActiveRecord::Base
Bar is missing a parent class.
```

**Comment by markburns** [comment]
BTW, happy to help contribute to the project if you can give pointers. We have a bit of time to look at improving our test suite, and one option is to look at using active_mocker to speed things up, if we can get it to work

**Comment by zeisler** [comment]
This was mostly just for debugging and I made the assumption that the model_dir would only contain ActiveRecord models. I could add a flag to ignore such cases. 

In my past projects I would put classes as you are mentioning in the lib directory.

**Comment by markburns** [comment]
That's not the case for us, and not an option really as the project is huge. Model doesn't necessarily mean the Active Record design pattern. It also doesn't necessarily mean ActiveRecord, the Rails gem.
You can have models that are not persisted. Or persistence related classes that are not necessarily domain concepts or 'models'.

I think it would make sense that the project defaults to just skipping over non AR subclasses. Would you agree? It would also solve the problem with `concerns` modules causing exceptions.

**Comment by zeisler** [comment]
I think the bast way to deal with this is to only have these show up when in debug mode and they should not count as a failure. Since this is not a blocking issue and only a nice to have I'm going to prioritize less than the other issues you've have raised.

**Comment by markburns** [comment]
I've got a local fix for this, so will get a test for it and do a PR
tomorrow and see what you think.
