### ISSUE TITLE
Some mechanism for ignoring DSL code in classes

### ISSUE THREAD

**Issue by markburns** [zeisler/active_mocker#49]
We have a bunch of classes failing to be generated due to using `state_machine` and `liquid_methods`. Both of which provide class level methods to the model class body.

Perhaps there could be a config file for various settings, including skipping over specific class methods in AR class definitions?

I can't imagine how support for something like a state machine gem would be easy and so we will probably just skip using active_mocker for any specs that fail due to that.

Happy to work on a PR for this, if you think it makes sense?

Or do you have any other ideas for an approach that would work?

**Comment by zeisler** [comment]
This will also most likely be a change in [dissociated_introspection](https://github.com/zeisler/dissociated_introspection). I think the best approach to this would be to ignore unknown methods like these, by using method_missing or some other means.
