### ISSUE TITLE
Be more optimistic with rake dependency (rake 11)

### ISSUE THREAD

**Issue by fatuhoku** [zeisler/active_mocker#52]
In the `active_mocker.gemspec`:

```rb
spec.add_runtime_dependency "rake", "~> 10.0"`
```

is too restrictive. I'm having to downgrade rake from v11 just to use the latest version of active_mocker.

**Comment by zeisler** [comment]
This is a current PR open for this.

https://github.com/zeisler/active_mocker/pull/43

I expect resolution by within the next day or so.

**Comment by fatuhoku** [comment]
@zeisler 🍻  that's just awesome.

**Comment by zeisler** [comment]
Fixed with https://github.com/zeisler/active_mocker/pull/43
