### ISSUE TITLE
Error message "To see more/less detail set error_verbosity = 0, 1, 2, 3" very unclear. How do you set error_verbosity with rake?

### ISSUE THREAD

**Issue by fatuhoku** [zeisler/active_mocker#54]
Being a Ruby newcomer it'd be nice to know the EXACT rake syntax I need to get verbose messages, so that I can understand why active_mocker is tripping up.

e.g. I just tried `rake error_verbosity=3 active_mocker:build` with no avail

**Comment by zeisler** [comment]
I agree this is not very clear. I will work to clarify it in the future. This is how it is done.

`ERROR_VERBOSITY=3 rake active_mocker:build`

**Comment by fatuhoku** [comment]
Thanks @zeisler I have made tiny progress. :P

**Comment by zeisler** [comment]
The error message should be changed to reflect this to make it easier for the next person.

**Comment by fatuhoku** [comment]
Awesome.
